[package]
name = 'kime-to'
version = '0.1.0'
edition = '2021'
license = 'AGPL-3.0-or-later'

[dependencies]
anyhow = '1.0.68'

[dependencies.kime-run-dir]
git = 'https://github.com/Riey/kime'
branch = 'develop'

[[bin]]
name = 'kime-to'
path = 'kime-to.rs'
