[package]
name = 'kime-to'
version = '0.1.0'
edition = '2021'
license = 'AGPL-3.0-or-later'

[dependencies.kime-run-dir]
git = 'https://github.com/Riey/kime'
branch = 'develop'

[[bin]]
name = 'kime-to'
path = 'kime-to.rs'

[profile.release]
strip = true
panic = 'abort'
lto = true
codegen-units = 1
opt-level = 'z'
