name: Build
on:
  push:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup install stable && rustup default stable
    - run: cargo build --release
    - name: copy kime-to
      run: >
        cp target/release/kime-to .
        && strip -s kime-to
        && chmod +x kime-to
    - uses: actions/upload-artifact@v3
      with:
        name: kime-to
        path: kime-to
